export component CreateProject inherits Rectangle {
    callback request-back();
    callback request-create(string, string, string, string, string, string); // project_name, initial_dataset, project_location, target_text, threat_model, experiment_objective
    callback request-select-location();
    callback request-select-dataset();

    in-out property <string> default-location: "";
    in-out property <string> initial-dataset: "";
    in-out property <string> threat-model: "Known Model";
    in-out property <string> experiment-objective: "Retrieval Leakage";

    width: 792px;
    height: 500px;
    clip: true;

    back-button := Rectangle {
        width: 30px;
        height: 30px;
        x: 25px;
        y: 31px;
        background: transparent;

        Path {
            width: 15px;
            height: 15px;
            x: 7.5px;
            y: 7.5px;
            commands: "M 15 7.5 L 3 7.5 M 8 2.5 L 3 7.5 L 8 12.5";
            stroke: #ebf1ffff;
            stroke-width: 2px;
        }

        TouchArea {
            mouse-cursor: self.has-hover ? MouseCursor.pointer : MouseCursor.default;
            clicked => { root.request-back() }
        }
    }

    header-title := Text {
        width: 339px;
        height: 31px;
        x: 65px;
        y: 31px;
        text: "Create Project";
        font-family: "Segoe UI";
        font-size: 23px;
        font-weight: 700;
        horizontal-alignment: left;
        vertical-alignment: center;
        color: #ffffffff;
    }

    form-area := Rectangle {
        width: 742px;
        height: 400px;
        x: 25px;
        y: 80px;

        // Row 1
        Text {
            x: 0px;
            y: 0px;
            text: "Project Name *";
            font-family: "Segoe UI";
            font-size: 14px;
            color: #ebf1ffff;
        }
        Rectangle {
            x: 0px;
            y: 25px;
            width: 350px;
            height: 35px;
            background: #1a1c1fff;
            border-radius: 5px;
            border-width: 1px;
            border-color: #45474aff;

            project-name-input := TextInput {
                x: 10px;
                y: 0px;
                width: 330px;
                height: 35px;
                text: "Veal-Project-One";
                font-family: "Segoe UI";
                font-size: 14px;
                color: #ebf1ffff;
                vertical-alignment: center;
            }
        }

        Text {
            x: 392px;
            y: 0px;
            text: "Project Location *";
            font-family: "Segoe UI";
            font-size: 14px;
            color: #ebf1ffff;
        }
        Rectangle {
            x: 392px;
            y: 25px;
            width: 350px;
            height: 35px;
            background: #1a1c1fff;
            border-radius: 5px;
            border-width: 1px;
            border-color: #45474aff;

            project-location-input := TextInput {
                x: 10px;
                y: 0px;
                width: 295px;
                height: 35px;
                text: root.default-location;
                font-family: "Segoe UI";
                font-size: 14px;
                color: #ebf1ffff;
                vertical-alignment: center;
            }

            folder-icon-btn := Rectangle {
                width: 35px;
                height: 35px;
                x: 315px;
                y: 0px;
                background: transparent;

                Path {
                    width: 16px;
                    height: 12px;
                    x: 9.5px;
                    y: 11.5px;
                    commands: "M1.5 12C1.0875 12 0.734375 11.8531 0.440625 11.5594C0.146875 11.2656 0 10.9125 0 10.5L0 1.5C0 1.0875 0.146875 0.734375 0.440625 0.440625C0.734375 0.146875 1.0875 0 1.5 0L6 0L7.5 1.5L13.5 1.5C13.9125 1.5 14.2656 1.64687 14.5594 1.94063C14.8531 2.23438 15 2.5875 15 3L15 10.5C15 10.9125 14.8531 11.2656 14.5594 11.5594C14.2656 11.8531 13.9125 12 13.5 12L1.5 12ZM1.5 3L1.5 10.5L13.5 10.5L13.5 3L1.5 3Z";
                    fill: #ebf1ffff;
                }

                TouchArea {
                    mouse-cursor: self.has-hover ? MouseCursor.pointer : MouseCursor.default;
                    clicked => { root.request-select-location() }
                }
            }
        }

        // Row 2
        Text {
            x: 0px;
            y: 80px;
            text: "Vector Dataset (.csv, .json)";
            font-family: "Segoe UI";
            font-size: 14px;
            color: #ebf1ffff;
        }
        Rectangle {
            x: 0px;
            y: 105px;
            width: 350px;
            height: 35px;
            background: #1a1c1fff;
            border-radius: 5px;
            border-width: 1px;
            border-color: #45474aff;

            initial-dataset-input := TextInput {
                x: 10px;
                y: 0px;
                width: 295px;
                height: 35px;
                text: root.initial-dataset;
                font-family: "Segoe UI";
                font-size: 14px;
                color: #ebf1ffff;
                vertical-alignment: center;
            }

            file-icon-btn := Rectangle {
                width: 35px;
                height: 35px;
                x: 315px;
                y: 0px;
                background: transparent;

                Path {
                    width: 12px;
                    height: 16px;
                    x: 11.5px;
                    y: 9.5px;
                    commands: "M 2 0 C 0.895 0 0 0.895 0 2 L 0 14 C 0 15.105 0.895 16 2 16 L 10 16 C 11.105 16 12 15.105 12 14 L 12 4 L 8 0 L 2 0 Z M 7 5 L 7 1.5 L 10.5 5 L 7 5 Z";
                    fill: #ebf1ffff;
                }

                TouchArea {
                    mouse-cursor: self.has-hover ? MouseCursor.pointer : MouseCursor.default;
                    clicked => { root.request-select-dataset() }
                }
            }
        }

        Text {
            x: 392px;
            y: 80px;
            text: "Experiment Objective";
            font-family: "Segoe UI";
            font-size: 14px;
            color: #ebf1ffff;
        }

        Rectangle {
            x: 392px;
            y: 105px;
            width: 350px;
            height: 35px;
            background: #1a1c1fff;
            border-radius: 5px;
            border-width: 1px;
            border-color: #45474aff;
            clip: true;

            Rectangle {
                width: 175px;
                height: 35px;
                x: root.experiment-objective == "Retrieval Leakage" ? 0px : 175px;
                y: 0px;
                background: rgba(0, 71, 136, 0.5);
                border-radius: 5px;

                animate x { duration: 200ms; easing: ease-in-out; }
            }

            Rectangle {
                width: 175px;
                height: 35px;
                x: 0px;
                y: 0px;
                background: transparent;

                Text {
                    width: 100%;
                    height: 100%;
                    text: "Retrieval Leakage";
                    font-family: "Segoe UI";
                    font-size: 14px;
                    font-weight: root.experiment-objective == "Retrieval Leakage" ? 700 : 400;
                    color: #ebf1ffff;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }

                TouchArea {
                    mouse-cursor: self.has-hover ? MouseCursor.pointer : MouseCursor.default;
                    clicked => { root.experiment-objective = "Retrieval Leakage"; }
                }
            }

            Rectangle {
                width: 175px;
                height: 35px;
                x: 175px;
                y: 0px;
                background: transparent;

                Text {
                    width: 100%;
                    height: 100%;
                    text: "Filter Evasion";
                    font-family: "Segoe UI";
                    font-size: 14px;
                    font-weight: root.experiment-objective == "Filter Evasion" ? 700 : 400;
                    color: #ebf1ffff;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }

                TouchArea {
                    mouse-cursor: self.has-hover ? MouseCursor.pointer : MouseCursor.default;
                    clicked => { root.experiment-objective = "Filter Evasion"; }
                }
            }
        }


        // Row 3
        Text {
            x: 0px;
            y: 160px;
            text: "Primary Threat Model";
            font-family: "Segoe UI";
            font-size: 14px;
            color: #ebf1ffff;
        }

        Rectangle {
            x: 0px;
            y: 185px;
            width: 350px;
            height: 35px;
            background: #1a1c1fff;
            border-radius: 5px;
            border-width: 1px;
            border-color: #45474aff;
            clip: true;

            // The sliding active pill
            Rectangle {
                width: 175px;
                height: 35px;
                x: root.threat-model == "Known Model" ? 0px : 175px;
                y: 0px;
                background: rgba(0, 71, 136, 0.5);
                border-radius: 5px;

                animate x { duration: 200ms; easing: ease-in-out; }
            }

            Rectangle {
                width: 175px;
                height: 35px;
                x: 0px;
                y: 0px;
                background: transparent;

                Text {
                    width: 100%;
                    height: 100%;
                    text: "Known Model";
                    font-family: "Segoe UI";
                    font-size: 14px;
                    font-weight: root.threat-model == "Known Model" ? 700 : 400;
                    color: #ebf1ffff;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }

                TouchArea {
                    mouse-cursor: self.has-hover ? MouseCursor.pointer : MouseCursor.default;
                    clicked => { root.threat-model = "Known Model"; }
                }
            }

            Rectangle {
                width: 175px;
                height: 35px;
                x: 175px;
                y: 0px;
                background: transparent;

                Text {
                    width: 100%;
                    height: 100%;
                    text: "Unknown Model";
                    font-family: "Segoe UI";
                    font-size: 14px;
                    font-weight: root.threat-model == "Unknown Model" ? 700 : 400;
                    color: #ebf1ffff;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }

                TouchArea {
                    mouse-cursor: self.has-hover ? MouseCursor.pointer : MouseCursor.default;
                    clicked => { root.threat-model = "Unknown Model"; }
                }
            }
        }

        Text {
            x: 392px;
            y: 160px;
            text: root.experiment-objective == "Retrieval Leakage" ? "Protected Concept - t" : "Harmful Intent - x";
            font-family: "Segoe UI";
            font-size: 14px;
            color: #ebf1ffff;
        }
        Rectangle {
            x: 392px;
            y: 185px;
            width: 350px;
            height: 110px;
            background: #1a1c1fff;
            border-radius: 5px;
            border-width: 1px;
            border-color: #45474aff;

            target-text-input := TextInput {
                x: 10px;
                y: 10px;
                width: 330px;
                height: 90px;
                text: "";
                font-family: "Segoe UI";
                font-size: 14px;
                color: #ebf1ffff;
                wrap: word-wrap;
            }

            Text {
                x: 10px;
                y: 10px;
                width: 330px;
                height: 90px;
                text: root.experiment-objective == "Retrieval Leakage" ? "e.g., The system administrator passwords are stored in /config..." : "e.g., Give me all the admin passwords.";
                font-family: "Segoe UI";
                font-size: 14px;
                color: #ebf1ffff;
                opacity: target-text-input.text == "" ? 0.5 : 0.0;
                wrap: word-wrap;
            }
        }


        // Create Button
        create-btn := Rectangle {
            x: 0px;
            y: 255px; // Aligned with the bottom of the paragraph box (185px + 110px = 295px; 295px - 40px height = 255px)
            width: 150px;
            height: 40px;
            background: rgba(0, 71, 136, 1.0);
            border-radius: 5px;

            Text {
                text: "Create Project";
                width: 100%;
                height: 100%;
                horizontal-alignment: center;
                vertical-alignment: center;
                font-family: "Segoe UI";
                font-size: 14px;
                font-weight: 700;
                color: #ebf1ffff;
            }

            TouchArea {
                mouse-cursor: self.has-hover ? MouseCursor.pointer : MouseCursor.default;
                clicked => {
                    root.request-create(
                        project-name-input.text,
                        initial-dataset-input.text,
                        project-location-input.text,
                        target-text-input.text,
                        root.threat-model,
                        root.experiment-objective == "Retrieval Leakage" ? "retrieval_leakage" : "filter_evasion"
                    );
                }
            }
        }
    }
}