import { Sidebar } from "sidebar.slint";
import { ProjectsView } from "projects-view.slint";

component UnderConstructionView inherits Rectangle {
    width: 100%;
    height: 100%;
    Text {
        text: "Under Construction - Coming in Future Updates";
        color: #ebf1ffff;
        font-family: "Segoe UI";
        font-size: 24px;
        horizontal-alignment: center;
        vertical-alignment: center;
        width: 100%;
        height: 100%;
    }
}

export component EntryPage inherits Rectangle {
    width: 1000px;
    height: 500px;
    background: #111316ff;
    clip: true;

    sidebar := Sidebar {
        x: 0px;
        y: 0px;
    }

    content-area := Rectangle {
        width: 792px;
        height: 500px;
        x: 208px;
        y: 0px;
        clip: true;

        if (sidebar.active-tab == "Projects") : projects_view := ProjectsView {

        }

        if (sidebar.active-tab != "Projects") : under_construction_view := UnderConstructionView {

        }
    }
}