import { Sidebar } from "sidebar.slint";
import { ProjectsView, RecentProject } from "projects-view.slint";
import { CreateProject } from "create-project.slint";

component UnderConstructionView inherits Rectangle {
    width: 100%;
    height: 100%;
    Text {
        text: "Under Construction - Coming in Future Updates";
        color: #ebf1ffff;
        font-family: "Segoe UI";
        font-size: 24px;
        horizontal-alignment: center;
        vertical-alignment: center;
        width: 100%;
        height: 100%;
    }
}

export component EntryPage inherits Rectangle {
    callback request-file-open();
    callback request-project-create(string, string, string, string, string, string);
    callback request-select-location();
    callback request-select-dataset();
    callback request-open-recent(string);

    in-out property <bool> creating_project: false;
    in-out property <string> default-location: "";
    in-out property <string> initial-dataset: "";
    in-out property <[RecentProject]> recent-projects: [];

    width: 1000px;
    height: 500px;
    background: #111316ff;
    clip: true;

    sidebar := Sidebar {
        x: 0px;
        y: 0px;
    }

    content-area := Rectangle {
        width: 792px;
        height: 500px;
        x: 208px;
        y: 0px;
        clip: true;

        if (sidebar.active-tab == "Projects" && !creating_project) : projects_view := ProjectsView {
            request-file-open => { root.request-file-open(); }
            request-create-project => { root.creating_project = true; }
            request-open-recent(path) => { root.request-open-recent(path); }
            recent-projects: root.recent-projects;
        }

        if (sidebar.active-tab == "Projects" && creating_project) : create_project_view := CreateProject {
            request-back => { root.creating_project = false; }
            request-create(project_name, initial_dataset, project_location, target_text, threat_model, experiment_objective) => {
                root.request-project-create(project_name, initial_dataset, project_location, target_text, threat_model, experiment_objective);
            }
            request-select-location => { root.request-select-location(); }
            request-select-dataset => { root.request-select-dataset(); }
            default-location: root.default-location;
            initial-dataset: root.initial-dataset;
        }

        if (sidebar.active-tab != "Projects") : under_construction_view := UnderConstructionView {

        }
    }
}