export component ProjectsView inherits Rectangle {
    callback request-file-open();
    callback request-create-project();
    in-out property <string> selected_file_path: "No file selected";
    width: 792px;
    height: 500px;
    clip: true;

    header-title := Text {
        width: 339px;
        height: 31px;
        x: 25px;
        y: 31px;
        text: "Vector Embedding Analysis Lab";
        font-family: "Segoe UI";
        font-size: 23px;
        font-weight: 700;
        horizontal-alignment: left;
        vertical-alignment: center;
        color: #ffffffff;
    }

    actions-row := Rectangle {
        width: 742px;
        height: 90px;
        x: 25px;
        y: 80px;

        new-project-card := Rectangle {
            width: 348px;
            height: 90px;
            x: 0px;
            y: 0px;
            background: #1a1c1fff;
            clip: true;
            border-radius: 8px;

            add-icon := Rectangle {
                width: 45px;
                height: 45px;
                x: 33px;
                y: 22.5px;
                background: transparent;
                clip: true;

                Path {
                    width: 26.25px;
                    height: 27.155172px;
                    x: 9.3750305px;
                    y: 11.684479px;
                    commands: "M11.25 15.5172L0 15.5172L0 11.6379L11.25 11.6379L11.25 0L15 0L15 11.6379L26.25 11.6379L26.25 15.5172L15 15.5172L15 27.1552L11.25 27.1552L11.25 15.5172Z";
                    fill-rule: nonzero;
                    stroke-width: 0.025px;
                    fill: #ebf1ffff;
                }
            }

            new-project-text-area := Rectangle {
                width: 214px;
                height: 68px;
                x: 94px;
                y: 11px;

                Text {
                    width: 214px;
                    height: 29px;
                    x: 0px;
                    y: 0px;
                    text: "New Project";
                    font-family: "Segoe UI";
                    font-size: 14px;
                    font-weight: 700;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                    color: #ebf1ffff;
                }

                Text {
                    width: 214px;
                    height: 39px;
                    x: 0px;
                    y: 29px;
                    text: "Create a new project to analyze vector datasets, inspect embeddings, and explore possible collisions";
                    font-family: "Segoe UI";
                    font-size: 10px;
                    font-weight: 300;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                    color: #ebf1ffff;
                    wrap: word-wrap;
                }
            }
            TouchArea {
                mouse-cursor: self.has-hover ? MouseCursor.pointer : MouseCursor.default;
                clicked => { root.request-create-project() }
            }
        }

        open-project-card := Rectangle {
            width: 348px;
            height: 90px;
            x: 394px;
            y: 0px;
            background: #1a1c1fff;
            clip: true;
            border-radius: 8px;

            folder-icon := Rectangle {
                width: 45px;
                height: 45px;
                x: 22px;
                y: 22.5px;
                background: transparent;
                clip: true;

                Path {
                    width: 40.3125px;
                    height: 30px;
                    x: 3.75px;
                    y: 7.5px;
                    commands: "M3.75 30C2.71875 30 1.83594 29.6328 1.10156 28.8984C0.367188 28.1641 0 27.2812 0 26.25L0 3.75C0 2.71875 0.367188 1.83594 1.10156 1.10156C1.83594 0.367188 2.71875 0 3.75 0L15 0L18.75 3.75L33.75 3.75C34.7812 3.75 35.6641 4.11719 36.3984 4.85156C37.1328 5.58594 37.5 6.46875 37.5 7.5L17.2031 7.5L13.4531 3.75L3.75 3.75L3.75 26.25L8.25 11.25L40.3125 11.25L35.4844 27.3281C35.2344 28.1406 34.7734 28.7891 34.1016 29.2734C33.4297 29.7578 32.6875 30 31.875 30L3.75 30ZM7.6875 26.25L31.875 26.25L35.25 15L11.0625 15L7.6875 26.25Z";
                    fill-rule: nonzero;
                    stroke-width: 0.025px;
                    fill: #ebf1ffff;
                }
            }

            open-project-text-area := Rectangle {
                width: 214px;
                height: 68px;
                x: 94px;
                y: 11px;

                Text {
                    width: 214px;
                    height: 29px;
                    x: 0px;
                    y: 0px;
                    text: "Open Project";
                    font-family: "Segoe UI";
                    font-size: 14px;
                    font-weight: 700;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                    color: #ebf1ffff;
                }

                Text {
                    width: 214px;
                    height: 39px;
                    x: 0px;
                    y: 29px;
                    text: "Open an existing .veal project to continue analyzing datasets, inspecting embeddings, or exploring collisions";
                    font-family: "Segoe UI";
                    font-size: 10px;
                    font-weight: 300;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                    color: #ebf1ffff;
                    wrap: word-wrap;
                }
            }
            TouchArea {
                mouse-cursor: self.has-hover ? MouseCursor.pointer : MouseCursor.default;
                clicked => { root.request-file-open() }
            }
        }
    }

    recent-projects-area := Rectangle {
        width: 738px;
        height: 291px;
        x: 29px;
        y: 188px;
        clip: true;

        Text {
            width: 102px;
            height: 19px;
            x: 0px;
            y: 15px;
            text: "Recent Projects";
            font-family: "Segoe UI";
            font-size: 14px;
            font-weight: 700;
            horizontal-alignment: left;
            vertical-alignment: center;
            color: #ebf1ffff;
        }

        table-wrapper := Rectangle {
            width: 738px;
            height: 248px;
            x: 0px;
            y: 43px;
            clip: true;
            border-radius: 8px;
            border-width: 1px;
            border-color: #1a1c1fff;

            table-header := Rectangle {
                width: 738px;
                height: 30px;
                x: 0px;
                y: 0px;
                background: #1a1c1fff;
                clip: true;

                Text {
                    width: 73px;
                    height: 16px;
                    x: 303px;
                    y: 7px;
                    text: "Last Modified";
                    font-family: "Segoe UI";
                    font-size: 12px;
                    font-weight: 400;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    color: #ebf1ffff;
                }

                Text {
                    width: 45px;
                    height: 16px;
                    x: 482px;
                    y: 7px;
                    text: "File Path";
                    font-family: "Segoe UI";
                    font-size: 12px;
                    font-weight: 400;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    color: #ebf1ffff;
                }

                Text {
                    width: 72px;
                    height: 16px;
                    x: 8px;
                    y: 7px;
                    text: "Project Name";
                    font-family: "Segoe UI";
                    font-size: 12px;
                    font-weight: 400;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    color: #ebf1ffff;
                }

                Rectangle { width: 1px; height: 15px; x: 288px; y: 8px; background: #76777bff; }
                Rectangle { width: 1px; height: 15px; x: 467px; y: 7px; background: #76777bff; }
            }

            table-row-1 := Rectangle {
                width: 738px;
                height: 30px;
                x: 0px;
                y: 30px;
                background: #45474aff;
                clip: true;

                Text { width: 107px; height: 16px; x: 304px; y: 7px; text: "Yesterday, 10:00 AM"; font-family: "Segoe UI"; font-size: 12px; color: #ebf1ffff; horizontal-alignment: center; vertical-alignment: center; }
                Text { width: 99px; height: 16px; x: 483px; y: 7px; text: "~\\Documents\\veal"; font-family: "Segoe UI"; font-size: 12px; color: #ebf1ffff; horizontal-alignment: center; vertical-alignment: center; }
                Text { width: 72px; height: 16px; x: 8px; y: 7px; text: "Project Name"; font-family: "Segoe UI"; font-size: 12px; color: #ebf1ffff; horizontal-alignment: center; vertical-alignment: center; }

                Rectangle { width: 1px; height: 15px; x: 288px; y: 8px; background: #76777bff; }
                Rectangle { width: 1px; height: 15px; x: 467px; y: 7px; background: #76777bff; }
            }

            table-row-2 := Rectangle {
                width: 738px;
                height: 30px;
                x: 0px;
                y: 60px;
                background: #5d5e62ff;
                clip: true;

                Text { width: 107px; height: 16px; x: 304px; y: 7px; text: "Yesterday, 10:00 AM"; font-family: "Segoe UI"; font-size: 12px; color: #ebf1ffff; horizontal-alignment: center; vertical-alignment: center; }
                Text { width: 99px; height: 16px; x: 483px; y: 7px; text: "~\\Documents\\veal"; font-family: "Segoe UI"; font-size: 12px; color: #ebf1ffff; horizontal-alignment: center; vertical-alignment: center; }
                Text { width: 72px; height: 16px; x: 8px; y: 7px; text: "Project Name"; font-family: "Segoe UI"; font-size: 12px; color: #ebf1ffff; horizontal-alignment: center; vertical-alignment: center; }

                Rectangle { width: 1px; height: 15px; x: 288px; y: 8px; background: #76777bff; }
                Rectangle { width: 1px; height: 15px; x: 467px; y: 7px; background: #76777bff; }
            }
        }
    }
}