import { EntryPage } from "components/entry.slint";

export component App inherits Window {
    in-out property <bool> is-project-loaded: false;
    callback request-file-open();
    title: "Welcome to Veal";
    property <image> logo: @image-url("assets/vector_logo.png");
    icon: logo;
    background: #1e1e1eff;
    width: 1000px;
    height: 500px;
    /*
    MenuBar {
        Menu {
            title: @tr("File");
        }
    }
    */
    // if (is-project-loaded) : MainAppView {}
    if (!is-project-loaded) : entry-page := EntryPage {
        x: 0px;
        y: 0px;
        request-file-open => { root.request-file-open(); }
    }
}