import { EntryPage } from "components/entry.slint";
import { RecentProject } from "components/projects-view.slint";

export component App inherits Window {
    in-out property <bool> is-project-loaded: false;
    callback request-file-open();
    callback request-project-create(string, string, string, string, string, string);
    callback request-select-location();
    callback request-select-dataset();
    callback request-open-recent(string);

    in-out property <string> default-location: "";
    in-out property <string> initial-dataset: "";
    in-out property <[RecentProject]> recent-projects: [];

    title: "Welcome to Veal";
    property <image> logo: @image-url("assets/vector_logo.png");
    icon: logo;
    background: #1e1e1eff;
    width: 1000px;
    height: 500px;
    /*
    MenuBar {
        Menu {
            title: @tr("File");
        }
    }
    */
    // if (is-project-loaded) : MainAppView {}
    if (!is-project-loaded) : entry-page := EntryPage {
        x: 0px;
        y: 0px;
        request-file-open => { root.request-file-open(); }
        request-project-create(pn, id, pl, tt, tm, eo) => { root.request-project-create(pn, id, pl, tt, tm, eo); }
        request-select-location => { root.request-select-location(); }
        request-select-dataset => { root.request-select-dataset(); }
        request-open-recent(path) => { root.request-open-recent(path); }
        default-location: root.default-location;
        initial-dataset: root.initial-dataset;
        recent-projects: root.recent-projects;
    }
}